services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`home.chat.${DOMAIN}`)"
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
      - "traefik.http.routers.open-webui.service=open-webui"
      - "traefik.http.routers.open-webui.tls.certresolver=dnsresolver"

volumes:
  open-webui:

networks:
  default:
    external: true
    name: traefiknet

