#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  echo "Refusing to overwrite existing ${ENV_FILE}"
  echo "Delete it first if you want to regenerate it."
  exit 1
fi

read -r -p "Domain for Traefik, e.g. example.com: " DOMAIN
DOMAIN="${DOMAIN//[[:space:]]/}"

if [[ -z "${DOMAIN}" ]]; then
  echo "DOMAIN is required."
  exit 1
fi

JWT_SECRET="$(openssl rand -hex 32)"
CSRF_SECRET="$(openssl rand -hex 32)"

cat > "${ENV_FILE}" <<EOF
# Public hostname base used by Traefik labels.
DOMAIN=${DOMAIN}

# ExcaliDash auth mode: local, oidc_enforced, or hybrid.
AUTH_MODE=local

# Stable random secrets generated by generate-env.sh.
JWT_SECRET=${JWT_SECRET}
CSRF_SECRET=${CSRF_SECRET}

# Optional OIDC settings if AUTH_MODE=hybrid or oidc_enforced.
# OIDC_PROVIDER_NAME=Authentik
# OIDC_ISSUER_URL=https://auth.example.com/application/o/excalidash/
# OIDC_CLIENT_ID=your-client-id
# OIDC_CLIENT_SECRET=your-client-secret
# OIDC_REDIRECT_URI=https://excalidash.${DOMAIN}/api/auth/oidc/callback
EOF

chmod 600 "${ENV_FILE}"

echo "Created ${ENV_FILE}"
echo "Review it before starting ExcaliDash."
